global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: jarvis-gateway
    static_configs:
      - targets: ["go-gateway:8000"]
    metrics_path: /metrics

  - job_name: jarvis-python-ai-service
    static_configs:
      - targets: ["python-ai-service:8100"]
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
